### ISSUE TITLE
Add new 3rd party resources & used by sections

### ISSUE THREAD

**Issue by webketje** [metalsmith/awesome-metalsmith#38]
### Used by
* NodeJS website: https://nodejs.org
* Moleculer (microservice framework for Node) CLI: https://moleculer.services/docs/0.14/moleculer-cli.html
* DooringX (D&D software development app) CLI : https://github.com/H5-Dooring/dooringx/blob/main/packages/dooringx-cli/src/modifyTemplate.ts
* Leo generator package (cross-dept template scaffolder): https://github.com/JDFED/leo
* Vue CLI until v2 (later replaced with vuepress): https://github.com/vuejs/vue-cli/tree/v2.9.3

### Listings
* https://www.intuz.com/top-static-site-generators
* https://superdevresources.com/static-site-generators/
* Metalsmith on libhunt: https://nodejs.libhunt.com/metalsmith-alternatives

### Resources
* Basic getting started in 10 languages: https://learntutorials.net/en/node-js/topic/6111/metalsmith
* Intermediate/advanced tutorial for GH pages: https://bengsfort.github.io/articles/metalsmith-blog-refactor/
* How static site generators work with Contentful: https://www.webstacks.com/blog/contentful-static-site-generators

**Comment by wernerglinka** [comment]
Added items to list. Resources are in blog lists, Basic getting started in 10 languages was a deadend
